### PR TITLE
README.md update

### PR DESCRIPTION
**Pull request by ClickoBito**
Please go through the information, add anything that might be missing and test so the installation process works before approving.

### CODE REVIEW

**Comment by buren** [comment]
👍 It would be awesome (and I think useful) if you want to follow the same pattern/template as we do in the README here: https://github.com/justarrived/just_match_api#commands (and [just-match-web](https://github.com/justarrived/just-match-web)). 

My favourite is the `script/*` convention. In the `script/` folder we have various convenience scripts for things such as start a local server, install/update the dependencies etc.

_References_

- JustMatch API [README](https://github.com/justarrived/just_match_api#commands).
- GitHubs blog post https://githubengineering.com/scripts-to-rule-them-all
- GitHubs scripts template https://github.com/github/scripts-to-rule-them-all

**Comment by buren** [comment]
Also another tip: use `yarn` instead of `npm`. Its basically `npm`, but faster, better stronger 😉 See https://code.facebook.com/posts/1840075619545360

**Comment by ClickoBito** [comment]
README.md updated to be in line with other JustArrived repositories.
Scripts section will have to be updated as scripts are added.
Yarn looks good and will test using it in the future, but leaving readme as is atm.

**Review by buren — COMMENTED** [review]
👍 👍

**Pull request merged**
